# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-15 04:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(re.compile('^[0-9]+$'), 'Edad no Valida', 'invalid')]),
        ),
    ]
